[package]
name = "demo"
version = "0.1.0"
authors = ["Fabrice <fabrice@schaub-dev.xyz>"]
edition = "2021"

[dependencies]
oprenta_components = { workspace = true }

dioxus = { version = "0.7.1", features = ["web"] }
dioxus-free-icons = { workspace = true, features = ["feather"] }
